export const Types = {
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
    UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
    GETONE_TODO_SUCCESS: "GETONE_TODO_SUCCESS",
    SHOWBUTTON_TODO_SUCCESS: "SHOWBUTTON_TODO_SUCCESS",
    COMPLETED_TODO_SUCCESS: "COMPLETED_TODO_SUCCESS",    
    CLEAR_SELECTED_TODO_SUCCESS: "CLEAR_SELECTED_TODO_SUCCESS",    
}
